// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0KMEi_nSEEdVYmyPkL-Gwnqk4iEs9-HI',
    appId: '1:513091290577:web:37528a32a18bc7db248cf0',
    messagingSenderId: '513091290577',
    projectId: 'my-mythology',
    authDomain: 'my-mythology.firebaseapp.com',
    storageBucket: 'my-mythology.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqXpvqrXFMJPSnF7lCT86a2jahbXmY18g',
    appId: '1:513091290577:android:44e9414fae6a41b0248cf0',
    messagingSenderId: '513091290577',
    projectId: 'my-mythology',
    storageBucket: 'my-mythology.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDPf721rnj9RG5YVQ61rrETKVt_Wo6xZc',
    appId: '1:513091290577:ios:0c71a96fb8c86c62248cf0',
    messagingSenderId: '513091290577',
    projectId: 'my-mythology',
    storageBucket: 'my-mythology.appspot.com',
    iosClientId: '513091290577-huj9htgbrl9pbku9aaq10423o8f0agut.apps.googleusercontent.com',
    iosBundleId: 'com.example.myMythology',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDPf721rnj9RG5YVQ61rrETKVt_Wo6xZc',
    appId: '1:513091290577:ios:0c71a96fb8c86c62248cf0',
    messagingSenderId: '513091290577',
    projectId: 'my-mythology',
    storageBucket: 'my-mythology.appspot.com',
    iosClientId: '513091290577-huj9htgbrl9pbku9aaq10423o8f0agut.apps.googleusercontent.com',
    iosBundleId: 'com.example.myMythology',
  );
}
